#!/usr/bin/env bash
#Replace this comment with your comment
log_file="apache-access.log"

if [ -e "$log_file" ]; then

    

    awk '{print $1, $9}' "$log_file"

else

    echo "The log file $log_file does not exist."

fi
