#!/usr/bin/env bash                                
# display all running PID                          
                                                   
while :                                            
do                                                 
        echo "I am alive!" >> /tmp/my_process      
        sleep 2                                    
done                                               
#!/usr/bin/env bash
# manage_my_process script

                                                  
start () {                                         
    ./manage_my_process &                          
    echo $! > /var/run/my_process.pid              
    echo "manage_my_process started"               
}                                                  
                                                   
stop () {                                          
    pkill -f "./manage_my_process"                 
    rm /var/run/my_process.pid                     
    echo "manage_my_process stopped"               
}                                                  
                                                   
restart () {                                       
    pkill -f "./manage_my_process"                 
    rm /var/run/my_process.pid                     
    ./manage_my_process &                          
    echo $! >> /var/run/my_process.pid             
    echo "manage_my_process restarted"             
}
case "$1" in                                       
   start) start ;;                                 
   stop)  stop;;                                   
   restart) restart;;                              
   *) echo "Usage: manage_my_process {start|stop|r\
estart}"                                           
                                                   
      ;;                                           
esac                                               
 
