#!/usr/bin/env bash
#a Bash script that:

Creates the file /var/run/myscript.pid containing its PID
Displays To infinity and beyond indefinitely
Displays I hate the kill command when receiving a SIGTERM signal
Displays Y U no love me?! when receiving a SIGINT signal
Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
START=0
END=1

echo "$$" >> /var/run/myscript.pid
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM

while [ "$START" -lt "$END" ];
do
	echo "To infinity and beyond"
	sleep 2
done
#!/usr/bin/env bash
#Write a manage_my_process Bash script that:
#Indefinitely writes I am alive! to the file /tmp/my_process
#In between every I am alive! message, the program should pause for 2 seconds
if [[ "$#" == "1" ]]; then
  if [[ "$1" == "start" ]]; then
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
  elif [[ "$1" == "stop" ]]; then
    if test -f "/var/run/my_process.pid"; then
      kill "$(cat /var/run/my_process.pid)"
    fi
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
  elif [[ "$1" == "restart" ]]; then
    # stop program
    if test -f "/var/run/my_process.pid"; then
      kill "$(cat /var/run/my_process.pid)"
    fi
    # start program
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
  else
    echo "Usage: manage_my_process {start|stop|restart}"
  fi
else
  echo "Usage: manage_my_process {start|stop|restart}"
fi
